/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        paper: '#F6F5F2',
        side: '#EFEDE8',
        line: '#E4E1EA',
        'line-strong': '#DDD9E4',
        divider: '#EEEBF2',
        ink: '#1D1A2B',
        'ink-2': '#3F3B4F',
        muted: '#625E73',
        faint: '#8F86B8',
        accent: '#5A3FD1',
        'accent-bright': '#6B52E8',
        'accent-ink': '#3A27A6',
        'accent-soft': '#E3DDF9',
        'accent-tint': '#F0ECFD',
        'accent-wash': '#F7F5FE',
        'accent-row': '#F4F1FE',
        'accent-line': '#CBC2F0',
        ok: '#1F7A4D',
        'ok-soft': '#E6F3EC',
        'ok-ink': '#175E3B',
        'ok-line': '#CFE6D9',
        warn: '#B26A00',
        'warn-soft': '#FBF1DF',
        'warn-ink': '#7A4700',
        night: '#14111F',
        'night-2': '#1C1830',
        'night-3': '#221D36',
        'night-line': '#2E2848',
        'night-edge': '#3A3452',
        lilac: '#B3A6F2',
        'lilac-2': '#BDB5E0',
        'lilac-3': '#D9D4EE',
      },
      fontFamily: {
        sans: ['Figtree', 'system-ui', 'sans-serif'],
        display: ['"Bricolage Grotesque"', 'Figtree', 'sans-serif'],
        tamil: ['"Noto Sans Tamil"', 'sans-serif'],
        deva: ['"Noto Sans Devanagari"', 'sans-serif'],
        telugu: ['"Noto Sans Telugu"', 'sans-serif'],
        kannada: ['"Noto Sans Kannada"', 'sans-serif'],
        malayalam: ['"Noto Sans Malayalam"', 'sans-serif'],
      },
      boxShadow: {
        seg: '0 1px 2px rgba(29,26,43,0.12)',
        lift: '0 6px 16px rgba(90,63,209,0.12)',
        play: '0 8px 24px rgba(0,0,0,0.35)',
      },
      keyframes: {
        spin: { to: { transform: 'rotate(360deg)' } },
      },
    },
  },
  plugins: [],
}
