
version: '3.8'

services:
  backend:
    build: ./backend
    container_name: audio_change_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/media:/app/media
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}

  frontend:
    build: ./frontend
    container_name: audio_change_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
